### PR TITLE
Core/Playerbots: Fixed SQL Query errors - Now usable with normal TC database.

### LINKED ISSUE #6: Installing issues
Hi

I'm trying to get this branch working however i'm getting tons or warnings.
I get it compiled with a few warnings, but when i run the server i'm getting a lot of database errors.

At random:
Warning: GetUInt32() on non-(medium)int field. Using type: TINY.

When rndbot init is put in console.
Warning: GetUInt64() on non-bigint field. Using type: LONG.

I'm using the normal characters and auth database from TC. Without any modifications.

Also i can add a bot with ".bot add Eolap" for example but it's just standing at a starting zone doing nothing but standing.

Some warnings in server.log:
Warning: Transaction only holds 1 query, consider removing Transaction context in code.
(getting tons of these)

Hope you can give some insight into this.

### PR DESCRIPTION
**Pull request by Kittnz**
- The reason this is huge is because it changed the text format to windows one.
- I just fixed the database uint's that were wrong.

Closes #6

### CODE REVIEW

**Comment by ike3** [comment]
Can you please re-make it without line ending changes? Too many conflicts

**Comment by Kittnz** [comment]
Sure ill redo it.

**Comment by Kittnz** [comment]
Didn't have time yet, ill try tonight.

**Comment by ike3** [comment]
Merged in [ai-0.36-63]

**Pull request closed without merging**
