### PR TITLE
3.3.5

### PR DESCRIPTION
**Pull request by ConradBunton**

### CODE REVIEW

**Comment by ConradBunton** [comment]
CMake Error at src/plugins/CMakeLists.txt:195 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "plugins".

**Comment by ghost** [comment]
Please close this PR, it won't be helpful at all to ike3. ike3 will decide when to do any more work at all to add new TrinityCore source in the mangosbot source. Remember, it takes a lot of work to do this, especially for 1 single person.

**Comment by ConradBunton** [comment]
Cant merge with the basic trinitycore. There's always an error about plugins directory. I give up.

**Comment by ConradBunton** [comment]
Just tried with the last updates.
MSVC 2015 x64
Boost 1.61.0
MySQL 5.7.11 x64

First error on CMake :
CMake Error at src/plugins/CMakeLists.txt:195 (install): install TARGETS given no ARCHIVE DESTINATION for static library target "plugins".

Ok... Replace that line by ARCHIVE DESTINATION "${CMAKE_INSTALL_PREFIX}"

But now, when I try to compil :

\src\plugins\playerbot\strategy\actions\sayaction.cpp(95): warning C4715: 'ai::SayAction::Execute': not all control paths return a value
 \src\plugins\playerbot\strategy\actions\TradeStatusAction.cpp(77): warning C4305: 'argument': truncation from 'double' to 'float'
\src\plugins\playerbot\strategy\actions\UseMeetingStoneAction.cpp(69): warning C4305: '+=': truncation from 'double' to 'float'
\src\plugins\playerbot\strategy\druid../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\druid\DruidAiObjectContext.cpp)
\src\plugins\playerbot\strategy\druid../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\druid\DruidTriggers.cpp)
\src\plugins\playerbot\strategy\hunter../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\hunter\HunterAiObjectContext.cpp)
\src\plugins\playerbot\strategy\hunter../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\hunter\HunterTriggers.cpp)
\src\plugins\playerbot\strategy\mage../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\mage\MageAiObjectContext.cpp)
\src\plugins\playerbot\strategy\mage../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\mage\MageTriggers.cpp)
\src\plugins\playerbot\strategy\paladin../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file src\plugins\playerbot\strategy\paladin\PaladinAiObjectContext.cpp)
\src\plugins\playerbot\strategy\paladin../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\paladin\PaladinTriggers.cpp)
\src\plugins\playerbot\strategy\priest../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\priest\PriestAiObjectContext.cpp)
\src\plugins\playerbot\strategy\priest../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\priest\PriestTriggers.cpp)
\src\plugins\playerbot\strategy\rogue../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\rogue\GenericRogueNonCombatStrategy.cpp)
\src\plugins\playerbot\strategy\rogue../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\rogue\RogueAiObjectContext.cpp)
\src\plugins\playerbot\strategy\rogue../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\rogue\RogueTriggers.cpp)
\src\plugins\playerbot\strategy\shaman../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\shaman\ShamanAiObjectContext.cpp)
\src\plugins\playerbot\strategy\shaman../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\shaman\ShamanTriggers.cpp)
\src\plugins\playerbot\strategy\triggers\GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\triggers\CureTriggers.cpp)
\src\plugins\playerbot\strategy\triggers\GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\triggers\GenericTriggers.cpp)
\src\plugins\playerbot\strategy\triggers\GenericTriggers.cpp(101): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning)
\src\plugins\playerbot\strategy\triggers\GenericTriggers.cpp(221): warning C4800: 'unsigned __int64': forcing value to bool 'true' or 'false' (performance warning)
\src\plugins\playerbot\strategy\triggers\HealthTriggers.cpp(14): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning)
\src\plugins\playerbot\strategy\values\StatsValues.cpp(53): warning C4800: 'uint32': forcing value to bool 'true' or 'false' (performance warning)
\src\plugins\playerbot\strategy\warlock../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\warlock\DpsWarlockStrategy.cpp)
\src\plugins\playerbot\strategy\warlock../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\warlock\WarlockAiObjectContext.cpp)
\src\plugins\playerbot\strategy\warlock../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\warlock\WarlockTriggers.cpp)
\src\plugins\playerbot\strategy\warrior../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\warrior\WarriorAiObjectContext.cpp)
\src\plugins\playerbot\strategy\warrior../triggers/GenericTriggers.h(256): warning C4800: 'Unit *': forcing value to bool 'true' or 'false' (performance warning) (compiling source file \src\plugins\playerbot\strategy\warrior\WarriorTriggers.cpp)

3>WarriorMultipliers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>GenericWarriorNonCombatStrategy.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>WarlockMultipliers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>WarlockActions.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>ShamanMultipliers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>ShamanActions.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>RogueTriggers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>RogueMultipliers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>RogueActions.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>PriestTriggers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>PriestMultipliers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>PaladinMultipliers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>PaladinActions.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>MageMultipliers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>HunterMultipliers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>DruidTriggers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>DruidMultipliers.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>NonCombatActions.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>GenericActions.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>Value.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>Multiplier.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>ActionBasket.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>TradeCategory.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
3>ConsumableCategory.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library

Any idea ?

**Pull request closed without merging**
